name: duolingo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/duo_samples/
      - assets/flags/
